[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-Trees-22
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-Trees-22
GtkTheme=oomox-Trees-22
IconTheme=oomox-Trees-22
MetacityTheme=oomox-Trees-22
